// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "SWAPI",
    "version": "1"
  },
  "paths": {
    "/api/{proceso}": {
      "get": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.get./api/{proceso}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.post./api/{proceso}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.put./api/{proceso}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.delete./api/{proceso}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/{proceso}/{metodo}": {
      "get": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.get./api/{proceso}/{metodo}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metodo",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.post./api/{proceso}/{metodo}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metodo",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "put": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.put./api/{proceso}/{metodo}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metodo",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "delete": {
        "summary": "film",
        "description": "",
        "tags": [
          "{proceso}"
        ],
        "operationId": "film.delete./api/{proceso}/{metodo}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proceso",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "metodo",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {}
};