const {
  SWAPI_URL,
  OMDB_URL,
  OMDB_API_KEY,
  DYNAMO_TABLE_FILM,
  DYNAMO_TABLE_FILM_CACHE,
  DYNAMO_TABLE_USER,
} = process.env;

export const api = {
  SWAPI_URL,
  OMDB_URL,
  OMDB_API_KEY,
  DYNAMO_TABLE_FILM,
  DYNAMO_TABLE_FILM_CACHE,
  DYNAMO_TABLE_USER,
};
